# Generated by Django 6.0.6 on 2026-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0059_achievement_solution_parts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="lagging_completion_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
